spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: gpt-review-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5432/math_review
    username: math
    password: review123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: kurikame73@gmail.com
    password: omsgomfrghbjzulv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  logging:
    level:
      org.springframework.security.web.authentication: DEBUG
jwt:
  secret: "base64:vW/PTau3eU0v0KakO3DQe+ORRWqEhCNDkWqERCqTSbs="
  expiration: 3600000

